spring.application.name=outil-formation
server.port=8081
spring.datasource.url=jdbc:h2:mem:outil-formation-db
spring.h2.console.enabled=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/outil-formation
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/outil-formation/protocol/openid-connect/certs
